#!/bin/sh
# Next.js standalone server entrypoint
# Runs the optimized standalone server generated by Next.js build
# Using Node.js runtime

# Start the Next.js standalone server with Node.js
# Port 8080
PORT=8080 node server.js 
